# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Brother.create(:name => 'Akhil Katta', :pledge_class => "Epsilon")
Brother.create(:name => 'Alan Do', :pledge_class => "Delta")
Brother.create(:name => 'Alex Akiyama', :pledge_class => "Gamma")
Brother.create(:name => 'Alyssa Wee', :pledge_class => "Gamma")
Brother.create(:name => 'Amrit Ayalur', :pledge_class => "Epsilon")
Brother.create(:name => 'Anant Agarwal', :pledge_class => "Gamma")
Brother.create(:name => 'Andy Zhang', :pledge_class => "Founding")
Brother.create(:name => 'Beau Dallas', :pledge_class => "Delta")
Brother.create(:name => 'Bryan Sieber', :pledge_class => "Delta")
Brother.create(:name => 'Bryan Tang', :pledge_class => "Epsilon")
Brother.create(:name => 'Claire Lei', :pledge_class => "Epsilon")
Brother.create(:name => 'Douglas Boyle', :pledge_class => "Epsilon")
Brother.create(:name => 'Eugenia Kang', :pledge_class => "Beta")
Brother.create(:name => 'Glenn Lee', :pledge_class => "Epsilon")
Brother.create(:name => 'Grace Chen', :pledge_class => "Gamma")
Brother.create(:name => 'Jasmine Stoy', :pledge_class => "Gamma")
Brother.create(:name => 'John Lee', :pledge_class => "Gamma")
Brother.create(:name => 'Justin Jiang', :pledge_class => "Epsilon")
Brother.create(:name => 'Justin Kang', :pledge_class => "Epsilon")
Brother.create(:name => 'Kenneth Le', :pledge_class => "Epsilon")
Brother.create(:name => 'Kirtan Upadhyaya', :pledge_class => "Alpha")
Brother.create(:name => 'Lanssie Ma', :pledge_class => "Beta")
Brother.create(:name => 'Mane Chakarian', :pledge_class => "Delta")
Brother.create(:name => 'Mauricio Baiocco', :pledge_class => "Delta")
Brother.create(:name => 'Michael McDonnell', :pledge_class => "Beta")
Brother.create(:name => 'Michael Perez', :pledge_class => "Delta")
Brother.create(:name => 'Prashan Dharmasena', :pledge_class => "Epsilon")
Brother.create(:name => 'Richard Zhang', :pledge_class => "Founding")
Brother.create(:name => 'Ryan Chun', :pledge_class => "Delta")
Brother.create(:name => 'Sherry Chen', :pledge_class => "Epsilon")
Brother.create(:name => 'Shun Yao', :pledge_class => "Gamma")
Brother.create(:name => 'Sorcha Evenhouse', :pledge_class => "Founding")
Brother.create(:name => 'Tom Yet', :pledge_class => "Gamma")
Brother.create(:name => 'Tricia Seow', :pledge_class => "Delta")
Brother.create(:name => 'Yash Desai', :pledge_class => "Epsilon")