Brother.create!([
  {name: "Akhil Katta", pledge_class: "Epsilon", avatar_file_name: "Akhil-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 522405, avatar_updated_at: "2014-01-09 00:51:26", status: "Pledge Parent"},
  {name: "Alan Do", pledge_class: "Delta", avatar_file_name: "Alan-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 570899, avatar_updated_at: "2014-01-09 00:52:05", status: "Pledge Master"},
  {name: "Alex Akiyama", pledge_class: "Gamma", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Active"},
  {name: "Alyssa Wee", pledge_class: "Gamma", avatar_file_name: "Alyssa-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 759181, avatar_updated_at: "2014-01-09 00:53:47", status: "Project Manager"},
  {name: "Amrit Ayalur", pledge_class: "Epsilon", avatar_file_name: "Amrit-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 548554, avatar_updated_at: "2014-01-09 00:54:29", status: "Webmaster"},
  {name: "Anant Agarwal", pledge_class: "Gamma", avatar_file_name: "Anant-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 514278, avatar_updated_at: "2014-01-09 00:54:57", status: "Operations VP"},
  {name: "Andy Zhang", pledge_class: "Founding", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Active"},
  {name: "Beau Dallas", pledge_class: "Delta", avatar_file_name: "Beau-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 597325, avatar_updated_at: "2014-01-09 00:55:22", status: "Pledge Educator"},
  {name: "Bryan Sieber", pledge_class: "Delta", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Active"},
  {name: "Bryan Tang", pledge_class: "Epsilon", avatar_file_name: "Bryan-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 464628, avatar_updated_at: "2014-01-09 00:55:45", status: "Pledge Parent"},
  {name: "Claire Lei", pledge_class: "Epsilon", avatar_file_name: "Claire-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 623343, avatar_updated_at: "2014-01-09 00:56:09", status: "Rush Chair"},
  {name: "Douglas Boyle", pledge_class: "Epsilon", avatar_file_name: "Doug-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 629158, avatar_updated_at: "2014-01-09 00:56:53", status: "Active"},
  {name: "Eugenia Kang", pledge_class: "Beta", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Active"},
  {name: "Glenn Lee", pledge_class: "Epsilon", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Marketing Chair"},
  {name: "Grace Chen", pledge_class: "Gamma", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "External VP"},
  {name: "Jasmine Stoy", pledge_class: "Gamma", avatar_file_name: "Jasmine-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 456529, avatar_updated_at: "2014-01-09 00:57:18", status: "Active"},
  {name: "John Lee", pledge_class: "Gamma", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Active"},
  {name: "Justin Jiang", pledge_class: "Epsilon", avatar_file_name: "JJ-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 652314, avatar_updated_at: "2014-01-09 00:58:23", status: "Treasurer"},
  {name: "Justin Kang", pledge_class: "Epsilon", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Active"},
  {name: "Kenneth Le", pledge_class: "Epsilon", avatar_file_name: "Kenneth-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 459632, avatar_updated_at: "2014-01-09 00:59:09", status: "Pledge Master"},
  {name: "Kirtan Upadhyaya", pledge_class: "Alpha", avatar_file_name: "Kirtan-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 337655, avatar_updated_at: "2014-01-09 01:00:57", status: "President"},
  {name: "Lanssie Ma", pledge_class: "Beta", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Active"},
  {name: "Mane Chakarian", pledge_class: "Delta", avatar_file_name: "Mane-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 802547, avatar_updated_at: "2014-01-09 01:01:23", status: "Project Manager"},
  {name: "Mauricio Baiocco", pledge_class: "Delta", avatar_file_name: "Mauricio-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 1039229, avatar_updated_at: "2014-01-09 01:03:45", status: "Active"},
  {name: "Michael McDonnell", pledge_class: "Beta", avatar_file_name: "Michael-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 498773, avatar_updated_at: "2014-01-09 01:04:26", status: "Social Chair"},
  {name: "Michael Perez", pledge_class: "Delta", avatar_file_name: "Perez-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 468148, avatar_updated_at: "2014-01-09 01:05:03", status: "Active"},
  {name: "Prashan Dharmasena", pledge_class: "Epsilon", avatar_file_name: "Prashan-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 681847, avatar_updated_at: "2014-01-09 01:05:43", status: "Webmaster"},
  {name: "Richard Zhang", pledge_class: "Founding", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Active"},
  {name: "Ryan Chun", pledge_class: "Delta", avatar_file_name: "Ryan-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 586027, avatar_updated_at: "2014-01-09 01:06:35", status: "Pledge Educator"},
  {name: "Sherry Chen", pledge_class: "Epsilon", avatar_file_name: "Sherry-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 473611, avatar_updated_at: "2014-01-09 01:07:39", status: "Rush Chair"},
  {name: "Shun Yao", pledge_class: "Gamma", avatar_file_name: "Shun-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 519082, avatar_updated_at: "2014-01-09 01:08:07", status: "Internal VP"},
  {name: "Sorcha Evenhouse", pledge_class: "Founding", avatar_file_name: "Sorcha-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 825297, avatar_updated_at: "2014-01-09 01:08:53", status: "Active"},
  {name: "Tom Yet", pledge_class: "Gamma", avatar_file_name: "Tom-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 665338, avatar_updated_at: "2014-01-09 01:09:24", status: "Active"},
  {name: "Tricia Seow", pledge_class: "Delta", avatar_file_name: "Tricia-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 480671, avatar_updated_at: "2014-01-09 01:10:19", status: "External VP"},
  {name: "Yash Desai", pledge_class: "Epsilon", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Active"},
  {name: "Derrick Cheng", pledge_class: "Beta", avatar_file_name: "Derrick-Square.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 655445, avatar_updated_at: "2014-01-09 00:56:31", status: "Active"},
  {name: "Andy Yang", pledge_class: "Founding", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Bill Kuang", pledge_class: "Founding", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Charles Li", pledge_class: "Founding", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Dana Zhang", pledge_class: "Founding", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "David Zeng", pledge_class: "Founding", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Emily Kuan", pledge_class: "Founding", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Eric Liu", pledge_class: "Founding", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Jenny Mi", pledge_class: "Founding", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Kathy Zheng", pledge_class: "Founding", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Paige Nguyen", pledge_class: "Founding", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Tiffany Lin", pledge_class: "Founding", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Youngshin Lee", pledge_class: "Founding", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Casey Finnerty", pledge_class: "Alpha", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Charles Murray", pledge_class: "Alpha", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Active"},
  {name: "Christina Oh", pledge_class: "Alpha", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Heather Hui", pledge_class: "Alpha", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Jeffrey Yang", pledge_class: "Alpha", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Katarina Du", pledge_class: "Alpha", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, statu s: "Alumnus"},
  {name: "Paul Duan", pledge_class: "Alpha", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Perry Yee", pledge_class: "Alpha", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Praneet Wadge", pledge_class: "Alpha", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Ritu Kiragi", pledge_class: "Alpha", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Ron Di", pledge_class: "Alpha", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Samantha Cano", pledge_class: "Alpha", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Active"},
  {name: "Spencer Poff", pledge_class: "Alpha", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Yuner Teh", pledge_class: "Alpha", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Bola Malek", pledge_class: "Beta", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Active"},
  {name: "Jayson Poon", pledge_class: "Beta", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Marcus Gedai", pledge_class: "Beta", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Riaz Ahmed", pledge_class: "Beta", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Shubin Li", pledge_class: "Beta", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Sylvia Lin", pledge_class: "Beta", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Victor Nadbitov", pledge_class: "Beta", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"},
  {name: "Albert An", pledge_class: "Gamma", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil, status: "Alumnus"}
])
